#!/bin/zsh

BOARD=wio_wm1110

pushd ..
export ZEPHYR_BASE=$PWD"/source/zephyr"
popd

ARM_OBJDUMP=$ZEPHYR_SDK_INSTALL_DIR/arm-zephyr-eabi/arm-zephyr-eabi/bin/objdump
NRFJPROG="./nrf-command-line-tools/bin/nrfjprog"

ZEPHYR=build/zephyr/zephyr.hex

CONFIG_LOG=/tmp/config.log
# LOG=--log=/tmp/nrfjprog.log

# rm -rf build

if [ ! -d ./build ] ; then

    date > $CONFIG_LOG

    cmake \
	-B build \
	-DCMAKE_RULE_MESSAGES=OFF \
	-D BOARD=$BOARD \
	$ZEPHYR_BASE/../wio-wm1110 \
	>>/tmp/config.log 2>&1
    cat /tmp/config.log
    wc  /tmp/config.log
fi

cmake --build build -j 4
rc=$?

if [ $rc -ne 0 ] ; then
    set-title "Error building code"
    exit 1
fi

$ARM_OBJDUMP -S -d build/zephyr/zephyr.elf > build/zephyr/zephyr.lst &

#
# Ready to flash code.
#
SENSOR="--snr 801049637"

#
# Need the 'eval' due to the quotes in the sensor value.
#
eval $NRFJPROG $SENSOR --recover --program $ZEPHYR --verify $LOG

#
# Start the Saleae logic analyzer and let it run in the backgound
#
#saleae_run.py &

#sleep 2

#
# Reset the board
#
eval $NRFJPROG $SENSOR --reset

set-title "Running..."

# sleep 1
# nrfjprog --readregs

#--------------------------------------------------------------------------------------------------
